### ISSUE TITLE
missing panel current

### ISSUE THREAD

**Issue by roessi** [KinDR007/VictronMPPT-ESPHOME#113]
hello,
First of all thx for the cool project!!

I noticed something.
The Battery current is mapped as panel current in the config of the ESP.
`panel_current:
      name: "${name} battery current"`
and the battery current is missing.

I tried to remap it.
`battery_current:
      name: "${name} battery current"`
`panel_current:
      name: "${name} panel current"`
but the expression panel_current: is a invalid option.

Please can you help me.
i think the interface delivers the data, because the battery and panel current is displayed on the vicrton mobile phone app.

**Comment by KinDR007** [comment]
Hi , mppt report panely power and voltage but not panel current 
You must calculate if you wish I=P/U

**Comment by Git-ChrisSc** [comment]
Hi,

here is my solution for this:

 - platform: template # Panel_current calculation 
    name: "Panel Current"
    id: panel_current
    unit_of_measurement: "A"
    lambda: |-
     float panel_current = id(panel_power).state / id(panel_voltage).state;
     return panel_current;
