### ISSUE TITLE
Tested Device Victron SmartSolar MPPT 100/15

### ISSUE THREAD

**Issue by Jarnsen** [KinDR007/VictronMPPT-ESPHOME#117]
I tested th Victron SmartSolar MPPT 100/15, it works perfectly

**Comment by drahdiwaberl** [comment]
BlueSolar MPPT 100 | 30 as well (at least the sensor which are defined in the example [here](https://github.com/KinDR007/VictronMPPT-ESPHOME#installation)

**Comment by ivoh95** [comment]
Tested a BlueSolar 75/15. All works correctly in the advanced example.
