### ISSUE TITLE
Entity sensor.smartshunt_depth_of_the_last_discharge is using native unit of measurement 'Ah' which is not a valid unit for the device class ('current')

### ISSUE THREAD

**Issue by dg1yds** [KinDR007/VictronMPPT-ESPHOME#121]
Hello,

I am using a Victron SmartShunt with your code; integrated into Home Assistant 2023.6.3.

At startup I have the following warning in the HA log:
`WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.smartshunt_depth_of_the_last_discharge (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'Ah' which is not a valid unit for the device class ('current') it is using; expected one of ['mA', 'A']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22`

Can you please check and update the configuration if applicable.
Thanks.

**Comment by syssi** [comment]
I've prepared a fix. 73 de DO2KSM
