### ISSUE TITLE
Occasional inaccurate values

### ISSUE THREAD

**Issue by JshStadler** [KinDR007/VictronMPPT-ESPHOME#125]
I have a Victron SmartShunt connected to an ESP32 to pull the battery stats into Home Assistant.

Occasionally (usually once a day, or every few days) I get a value spiking down to exactly 9.1% SOC for the battery or 2.7V battery voltage (both doesn't happen at the same time, and the spike seems to only happen while the battery is at 91%, or 27V). This messes up the statistics a bit. 

Has anyone else experienced this? Is there a way to ignore an extreme outlier value like this?

![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/37085670/bb7f802a-407c-4889-8dac-116e1beebaef)
![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/37085670/5113f58f-c7bb-4e26-9e2c-e3a35faa96e0)

**Comment by syssi** [comment]
You could apply a `quantile` filter to the affected sensors: https://esphome.io/components/sensor/index.html

**Comment by JshStadler** [comment]
@syssi 
Thanks, quantile looks promising, I've setup the filter to ignore the specific values for now (as this should cause the least amount of overhead/delay), if I see any more spikes, I'll setup the quantile filter.
