### ISSUE TITLE
victron mppt 150/60

### ISSUE THREAD

**Issue by cristof48** [KinDR007/VictronMPPT-ESPHOME#126]
helo, there is something strange with Victron mppt 150/60. I receive only half the data.
I have tested with 2 ESP32, and it's same.

I also run an mppt victron 150/35 with the code and it's all good, 
with same esp32 and code, it's all good for mppt 150/35 but only a few data for mppt 150/60

**Comment by dnwalker68** [comment]
I connected a Wemos D1 Mini to my solar charger and flashed it with the current ESPHome version. Here I have the problem that not all data is transferred. If I compile the same Yaml file with an older version of ESPHome, it works without any problems. I tried this with three different ESP modules to rule out a possible defect there. But it is up to the ESPHome version because the error occurs with all blocks.

**Comment by Roving-Ronin** [comment]
@cristof48 
Would you be able to confirm what data/sensors your able to access on your SmartSolar MPPT 150/35 ?
I'm following the examples and only getting a few sensors, such as the basics (voltage, yield today/yesterday, max load today etc), but nothing like SoC, Load, battery temp, amount of charged energy / discharged energy etc.

Thanks in Advance.

**Comment by KinDR007** [comment]
> @cristof48 Would you be able to confirm what data/sensors your able to access on your SmartSolar MPPT 150/35 ? I'm following the examples and only getting a few sensors, such as the basics (voltage, yield today/yesterday, max load today etc), but nothing like SoC, Load, battery temp, amount of charged energy / discharged energy etc.
> 
> Thanks in Advance.

Hi ,
```SoC, Load, amount of charged energy / discharged energy etc.```  does not report mppt but smartshunt or BVM

**Comment by KinDR007** [comment]
Hi , look to this file in root of repo

smartsolar-mppt-esp8266-example.yaml

**Comment by Roving-Ronin** [comment]
@KinDR007 OK I saw that and the 'advanced' version, tried adding the SoC and other sensors and go no reading back from the ESP for those sensors, hence my wondering if all those sensors in the base / advanced examples should work for a 100/35, or of a 'higher end' model was needed to support those sensors / features.

From what you're saying, I take it the 100/35 should be able to automatically read things like battery SoC?

**Comment by KinDR007** [comment]
SoC is only reported by smartshut or bvm .mppt never reports SoC , mppt doesn't know how much current is drawn from the battery so it has no way to calculate SoC

**Comment by KinDR007** [comment]
Victron has two series . Smart and Blue . The smart series has both bluetooth and "ve.direct" .The blue series has only "ve.direct" otherwise they are practically the same with minor exceptions . To measure the battery charge status it is necessary to use a device other than the solar charger mppt
