### ISSUE TITLE
Sending commands

### ISSUE THREAD

**Issue by RobertLukan** [KinDR007/VictronMPPT-ESPHOME#129]
Is there any option to send command such as Charger Enabled (On/Off) ? I understand that additional pin on ESP would have to be connected to RX on MPPT charger.

**Comment by KinDR007** [comment]
> Is there any option to send command such as Charger Enabled (On/Off) ? I understand that additional pin on ESP would have to be connected to RX on MPPT charger. 

Hi unfortunately not . The protocol used is read only it can't send any commands
