### ISSUE TITLE
Errors with SmartSolar MQTT 100/50

### ISSUE THREAD

**Issue by Flori261** [KinDR007/VictronMPPT-ESPHOME#145]
Hello everyone,
I have tried to integrate my SmartSolar MPPT 100/50 with an ESP8266. However, I only receive the Panel Power value. 

I have installed the debug program. Here is the LOG

Do you see a possibility to implement this. Does the software need to be adapted or am I doing something wrong?

[logs_victron-solar10050-esp_logs.txt](https://github.com/KinDR007/VictronMPPT-ESPHOME/files/13955704/logs_victron-solar10050-esp_logs.txt)

**Comment by KinDR007** [comment]
probably same as here 

https://github.com/KinDR007/VictronMPPT-ESPHOME/issues/143

**Comment by Flori261** [comment]
Hey thanks for the reply,

I use a nodemcuv2 Amica without an second Rx tx pin. What pin should I use instead of D7?

Will a swap to a WeMos d1 mini help?

**Comment by Flori261** [comment]
Change to WeMos d1 mini was not successful

**Comment by Flori261** [comment]
Changed the wiring and the software on the nodemcu to talk on gpio3 (Rx) Not working at all.

**Comment by KinDR007** [comment]
Please send foto of wiring (of mppt and esp side)and yaml for esphome

**Comment by KinDR007** [comment]
And plase check settings of mppt "normal communication must be selected ![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/61905170/fe114adb-bdc1-45d2-9282-a6ff29343b20)
