### ISSUE TITLE
Typo in smartsolar-mppt-esp8266-example.yaml

### ISSUE THREAD

**Issue by eMaitcH75** [KinDR007/VictronMPPT-ESPHOME#148]
Good evening.
I was wondering about the "Panel Current" in my Home Assistant. Then i realize that "Panel Current" shows "Battery Current"...
Line 61 in "smartsolar-mppt-esp8266-example.yaml" says "name: "${name} panel current"", but it should have "name: "${name} battery current", right?

https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartsolar-mppt-esp8266-example.yaml

**Comment by KinDR007** [comment]
Yes you right
