### ISSUE TITLE
[W][victron:093] Last transmission too long ago

### ISSUE THREAD

**Issue by supp0815** [KinDR007/VictronMPPT-ESPHOME#152]
Hey there,

I don't think it's a software issue. I had it running a year ago. System was down for a while. Today I connected everything including a new D1 mini. Data from TX on the mppt to D7 (GPIO13). When connected I don't get any victron data and instead the "[W][victron:093] Last transmission too long ago" message in the logs. Removing the data cable, message disappears. 

System is, 12V battery goes to a linear actuator and 5V regulator, from the regulator to D1 mini. D1 controls the relays and a data line on D7 to the MPPT 100/30.  

Any ideas what's missing?

![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/106332092/a0baa363-5314-4b79-a173-04861d3c722d)

**Comment by KinDR007** [comment]
What mppt ? Blue or smart? How is the "ve.direct" port set? How sure are you about the wiring ? Any photos of wiring ?

**Comment by supp0815** [comment]
> What mppt ? Blue or smart? How is the "ve.direct" port set? How sure are you about the wiring ? Any photos of wiring ? 

It's the Victron Energy BlueSolar MPPT. The wiring should be fine, as is said I was using it for a while and it was working with the same code.

![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/106332092/ca4a7afc-12ab-411f-b9a7-bea599d27d09)

D7 to MPPT

![image](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/106332092/4602331d-49fb-4619-9041-9dac9b4b0578)

**Comment by supp0815** [comment]
Alright, I think it was the D1 mini. I tried another ESP and connected that one separately straight to the victron and powered by the 12V battery (using a regulator). Works fine, no issues.
