### ISSUE TITLE
Smart Victron Inverter has new PID Value

### ISSUE THREAD

**Issue by mdframe** [KinDR007/VictronMPPT-ESPHOME#167]
I am using the Smart Phoenix Inverter, 12v/1200w, and the PID is showing as 0xA2F9 in the UART log even though VE.DirectProtocol is showing this product id as 0xA279.  Maybe a typo in the documentation?

**Comment by syssi** [comment]
This is the 120V version?

**Comment by mdframe** [comment]
Ah, yes it is.

**Comment by syssi** [comment]
I've added the probably new PID to the list.

**Comment by mdframe** [comment]
Thank you, works perfectly now!  I appreciate the quick response to getting a fix into the code.
