### ISSUE TITLE
Is a battery capacity sensor for the SmartShunt possible?

### ISSUE THREAD

**Issue by NNenya** [KinDR007/VictronMPPT-ESPHOME#176]
Would be good to get (and possibly update) SmartShunt battery capacity data.

**Comment by KinDR007** [comment]
Hi,

Smartshunt only reports the remaining capacity in the batteries. So by creating the template :battery capacity-reporting capacity remaining you get what you need

**Comment by NNenya** [comment]
I am referring to this SmartShunt parameter ...
![WhatsApp Image 2024-08-23 at 16 40 47_bc3e21ea](https://github.com/user-attachments/assets/fbdf6962-c716-4934-9104-86de9c0684b4)

**Comment by KinDR007** [comment]
No I'm sorry but smartshunt does not report this value via ve.direct port
