### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RFDarter** [KinDR007/VictronMPPT-ESPHOME#188]
Is there a way to also control the mppt,?
I have a remote setup that needs every Wh it can get, so installing a raspi with venus os would consume to much power.

It consists of the battery, mppt, lte-router, wlan camera.
So I could simply add a esp which sends data to my home and do all the calculations and control there.

**Comment by syssi** [comment]
This implementation is read-only. The victron device transmits a ASCII message periodically. This project is just a decoder. The HEX protocol needs to be implemented forbread-write operations.

**Comment by RFDarter** [comment]
> This implementation is read-only. The victron device transmits a ASCII message periodically. This project is just a decoder. The HEX protocol needs to be implemented forbread-write operations.

I guess nobody has done that already?

**Comment by KinDR007** [comment]
This feature it's not planned
