### ISSUE TITLE
Smart Shunt 500A level too low? 

### ISSUE THREAD

**Issue by mariusvaida** [KinDR007/VictronMPPT-ESPHOME#189]
I purchased a "Victron Energy SmartShunt 500A/50mV" and i have trouble wiring into Esphome.
First, the two end pins (first and last) don't have any tension using a multimeter, second, i checked using an oscilloscope and i only get some data on the first two pins (looking as in the image bellow), which according to pinouts i found should be TX and VCC. On first pin (which should be GND) and TX pin i get nothing.
The issue is that even on the pins i get signal, the level is too low, about 0.5V on high and the esp board doesn't recognize it. As a workaround i added a 1k resistor between 3.3V and TX pin and now it works, but i don't understand why the level is that low.
Am i missing something? I should provide 3.3V to the shunt on the connector?
Please help me sorting this out.

Thank you.
![1-3](https://github.com/user-attachments/assets/561b49fa-273b-4237-b376-cdf0f1773e5a)

**Comment by KinDR007** [comment]
Hi,Look to readme 
https://github.com/KinDR007/VictronMPPT-ESPHOME

Section of diy cable..

**Comment by mariusvaida** [comment]
@KinDR007 I saw that section, but according to that he JST connector pinout, the TX pin is right to the V+ pin, not to the GND. Now, even if the last pin in my case is the GND, the level is still an issue as it's very low.
As I stated before, I checked with an oscilloscope and this is the only working combination that outputs something. 
For now it works with the 1k resistor, but that is an improvisation.

**Comment by syssi** [comment]
Could your try to talk to the manufacturer and share the feedback?

**Comment by KinDR007** [comment]
I have the same smartshunt and uart works as it should I recommend to contact the manufacturer or complain to the supplier

**Comment by mariusvaida** [comment]
Sorted out finally! After reading your messages I coupled again the oscilloscope, but now I used the ground from the shunt to see if the signal is higher and it was 3.3V. Strange enough after this, the ground pin started working, so I suspect a loose connection on the ground pin. I will search another one.
Thank you very much for the help.
