### ISSUE TITLE
Question for monitor a second victron input 

### ISSUE THREAD

**Issue by kead** [KinDR007/VictronMPPT-ESPHOME#2]
Congratulations and thank you for this fantastic integration!! 
I passed the code on esp32 (it has more power) and I would like to use the same to monitor a Victron BMV-712 Battery monitor as well.
Is it possible in your opinion?

**Comment by KinDR007** [comment]
Hi for BMV use my other component "SmartShunt esphome " btw bmv and smartshunt has a same properties 

https://github.com/KinDR007/VictronSmartShunt-ESPHOME

**Comment by kead** [comment]
i saw the other project, but i didn't understand if they can be used together in the same esp32 (or esp8266)... 
Thank you

**Comment by KinDR007** [comment]
Hi,

theoretically they could work on one esp .. but .. mppt and bmv (including smartshunt) have some properties named the same which will cause a problem .. therefore i recommend to use one esp for each victron device
