### ISSUE TITLE
Some errors 

### ISSUE THREAD

**Issue by lucasimons** [KinDR007/VictronMPPT-ESPHOME#21]
Hi I am using this software with a 100/20 l mppt, I have encountered problems with decimals let me explain better, some times for example the battery voltage is 26v but the sensor sends 0.26v, this also happens to the total energy I already have put a filter that averages but is not enough
![Screenshot_20210916_204803_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/67467751/133669138-ae5b387d-d642-49c9-a63e-782e31612e36.jpg)

**Comment by syssi** [comment]
Could you try to provide the raw data of your solar charger?

**Comment by lucasimons** [comment]
![Immagine 2021-09-17 094946](https://user-images.githubusercontent.com/67467751/133745559-0de1d991-ad13-4299-b197-7d38f799825f.jpg)
![vic](https://user-images.githubusercontent.com/67467751/133745567-d2dbb5db-7f9c-4cb2-b2a8-4eff728f8c4e.jpg)

**Comment by KinDR007** [comment]
@lucasimons 

may i ask how are you wiring ?

**Comment by lucasimons** [comment]
I have connected the tx to D7 e gnd to gnd... I would not want my nodemcu to go into crisis with esp8266 because it actually sends a lot of data it is not possible to decrease the refresh rate, as soon as I get it I will use an esp 32 to see if I solve

**Comment by KinDR007** [comment]
@lucasimons 

power supply how did you deal with?  external source?  or stepdown from Battery

**Comment by lucasimons** [comment]
Yes I have the 24v battery and a victron orion 24v to 12v converter and then connected a quick charge 3.0 module that powers a raspberry and the nodemcu however I think it's like putting a step down 24 to 5

**Comment by KinDR007** [comment]
Ok , 
Please disconect gnd from ve.direct port and try 
(
Ve.direct connected only tx
Power supply vcc and gnd from step down 
)
