### ISSUE TITLE
Working for BVM-702?

### ISSUE THREAD

**Issue by climbingblake** [KinDR007/VictronMPPT-ESPHOME#42]
I have both a MPPT and a BVM, on separate ESP8266s.  This code works perfectly on my MPPT, but im hoping to use it or the majority of it forked to work with my BVM.  I see there are some references in the code for BVM.  Does anyone have it working for BVM?

**Comment by KinDR007** [comment]
> I have both a MPPT and a BVM, on separate ESP8266s.  This code works perfectly on my MPPT, but im hoping to use it or the majority of it forked to work with my BVM.  I see there are some references in the code for BVM.  Does anyone have it working for BVM?

For BMV and smartshunt look here https://github.com/KinDR007/VictronSmartShunt-ESPHOME
