### ISSUE TITLE
Mppt 100/20 not work

### ISSUE THREAD

**Issue by lucasimons** [KinDR007/VictronMPPT-ESPHOME#6]
Hi,
i tried to use the custom component with espHome but i have this warnig
![Immagine 2021-08-28 182627](https://user-images.githubusercontent.com/67467751/131224625-47cbfd4d-02db-4c05-a4fd-658385927b90.jpg)
![Victron_cable_unit_pinout](https://user-images.githubusercontent.com/67467751/131224627-ac19b568-6a2e-4ae8-a3ed-91b59386660c.jpg)

**Comment by syssi** [comment]
Did you try to swap the RX/TX?

**Comment by lucasimons** [comment]
Should I reverse the cable on the mppt controller?

**Comment by syssi** [comment]
D7 must be connected to RXI. Don't connect TXO because the communication is read-only / receiving-only.

**Comment by lucasimons** [comment]
yes but also in the photo he connected the first and third pin which are gnd and tx then obviously the d7 sara rx that is, it reads the data sent by the victron

**Comment by syssi** [comment]
I assume the photo is mirrored compared to your picture because the red wire is connected to GND and is the most right position at the connector. Do you own a multimeter to messer the voltage between the outer pins? So you could make sure which one is GND.

**Comment by lucasimons** [comment]
yes I checked and the ground in my controller is on the left I do not wish that something had broken because initially I had connected in the wrong position that is gnt to 5v and d7 to rx .... it seems that the connection is unstable I would not have broken something

**Comment by syssi** [comment]
Do you see/receive any sensor values of the solar charger? Your debug output contains `uptime` and `wifi quality` measurements only. It looks like you are unable to receive any data of the charger.

**Comment by lucasimons** [comment]
i don t  see any solar sensor only the wifi streght
![Immagine 2021-08-29 122426](https://user-images.githubusercontent.com/67467751/131247161-64ab6fe3-5da3-4235-bad3-71eb874cc0a1.jpg)

**Comment by syssi** [comment]
Could you post your configuration yaml (without secrets)? You could increase the log level of the uart to monitor the traffic between your ESP and the victron:

```
logger:
  baud_rate: 0
  level: VERY_VERBOSE
  logs:
    uart: VERY_VERBOSE 
    uart_esp8266: VERY_VERBOSE 
    api.service: WARN
    ota: WARN
    sensor: DEBUG
    victron: DEBUG
```

**Comment by lucasimons** [comment]
after doing some tests I was able to make it work, now I simply have to fix the stability because I notice constant disconnections to the home assistant

**Comment by syssi** [comment]
Could you share your solution/mistakes/findings?

**Comment by KinDR007** [comment]
And this wiring not works ?
[](https://community.home-assistant.io/t/victron-energy-vedirect-bluetooth/20726/66?u=kindr)

**Comment by KinDR007** [comment]
> D7 must be connected to RXI. Don't connect TXO because the communication is read-only / receiving-only. Take a look at this photo:
> 
> 
> 
> https://community.home-assistant.io/t/victron-energy-vedirect-bluetooth/20726/43?u=syssi

D7 = rx pin on wemos 
Ve.direct tx pin connect to D7 pin its ok

**Comment by KinDR007** [comment]
> after doing some tests I was able to make it work, now I simply have to fix the stability because I notice constant disconnections to the home assistant

hi how do you solve the power supply?  it keeps me going and the connection doesn't fall
![image](https://user-images.githubusercontent.com/61905170/131405125-6f8bdd34-401c-491a-b12a-eeb97a9dc2ab.jpeg)

**Comment by lucasimons** [comment]
I did not make substantial changes simply I checked the connections and it worked then I took a d1 mini and used it to control a relay and an ac dimmer and I also connected the victron to pin d1 I don't know if this creates problems, but I don't think so and now I have also changed the power supply but it seems to disconnect anyway

esphome:
  name: fotovoltaico
  platform: ESP8266
  board: d1_mini
  includes:
      - custom_components/victron/victron.h
substitutions:
    lower_devicename: "victron"
    devicename: "SmartSolar_100_20" 
    config_version: "v2021.05.30"
    wifi_fast_connect: "false"
   # wifi_reboot_timeout: 0s
    accuracy: "2"


wifi:
  ssid: 
  password: 
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fotovoltaico Fallback Hotspot"
    password: "R8aNhGpg7EA3"


captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: VERY_VERBOSE
  logs:
    uart: VERY_VERBOSE 
    uart_esp8266: VERY_VERBOSE 
    api.service: WARN
    ota: WARN
    sensor: DEBUG
    victron: DEBUG

# Enable Home Assistant API
api:

ota:


uart:

- id: uart_bus
  tx_pin: D4 # not connected !! 
  rx_pin: D1 # use olny this pin and GND to MPPT chrager
  baud_rate: 19200 
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256
  
victron:
  uart_id: uart_bus  

sensor:  

  - platform: victron
    panel_voltage:
      name: "Pannello Tensione" 
      id: pv
    battery_voltage:
      name: "Batteria Tensione"  
      id: bv
    battery_current:
      name: "Batteria Corrente" 
      id: bc
    load_current:
      name: "Corrente carichi DC" 
      id: load_current
    max_power_yesterday:  
      name: "Massima potenza Ieri" 
      id: max_power_yesterday
    max_power_today:  
      name: "Massima potenza Oggi" 
      id: max_power_today
      accuracy_decimals: ${accuracy}
    yield_total:
      name: "Energia totale pannelli"   
      id: yield_total
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}
    yield_yesterday:
      name: "Energia pannelli Ieri "  
      id: yield_yesterday
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}
    yield_today:
      name: "Energia pannelli Oggi"  
      id: yt
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}
    panel_power:
      name: "Potenza Pannelli"  
      id: panel_power
    day_number:
      name: "Day sequence number"  
      id: day_number
      icon: "mdi:calendar-today"
    charger_text:
      name: "Charger state"
      id: ct
    error_text:
      name: "Error code"  
      id: et
    tracker_text:
      name: "Tracker operation"  
      id: tt
    fw_version:
      name: "Fw version"  
      id: fw
    pid:
      name: "PID"  
      id: pid  
 

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: D7
    zero_cross_pin:
      number: D8
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Resistenza Dimmer  



    
switch:
  - platform: gpio
    pin: D3
    
    name: "Inverter"      # Modificare nome a piacimento da esporre in Home Assistant
  - platform: restart
    name: "Auto Restart"
    id: restart_switch
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 50
        hours: 3
        days_of_week: MON-SUN
        then:
           - switch.toggle: restart_switch
    id: homeassistant_time

**Comment by KinDR007** [comment]
Pin D3 = flash change to other pin 

![image](https://user-images.githubusercontent.com/61905170/131411357-b5c07063-70e5-4fef-8ed8-9211a2cab4bf.jpeg)

**Comment by lucasimons** [comment]
last night I tried to put the relay on pin d4 but about every 1000 seconds I had a disconnection, now I tried with another wemos d1 mini that I used previously for the dimmer and the relay, I will update you if I have solved the problem

**Comment by lucasimons** [comment]
I tried to change the power supply and micro USB cable but I always encountered that problem now I used a step down converter 12v to 5v I see if it improves, I update you if I have solved or found something![Screenshot_20210831_215230_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/67467751/131572577-c41edab5-d1ca-484c-be82-fcf5b58f3baa.jpg)

**Comment by KinDR007** [comment]
> I tried to change the power supply and micro USB cable but I always encountered that problem now I used a step down converter 12v to 5v I see if it improves, I update you if I have solved or found something![Screenshot_20210831_215230_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/67467751/131572577-c41edab5-d1ca-484c-be82-fcf5b58f3baa.jpg)

powered by battery pack connected to mppt?  if so do not connect gnd from stepdown to wemos

**Comment by lucasimons** [comment]
I should have solved the problem by changing the wemos d1 mini with a nodemcu esp8266 now 5000 seconds have already passed and I think I have solved it, but I also changed the connections in this way

- id: uart_bus
  tx_pin: D8 # not connected !! 
  rx_pin: GPIO13 # use olny this pin and GND to MPPT chrager
  baud_rate: 19200 
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256
  
    
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO12
    zero_cross_pin:
      number: GPIO14
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Resistenza Dimmer  

switch:
  - platform: gpio
    pin: D1
    
    name: "Inverter"


today i will also try this https://github.com/syssi/esphome-pipsolar made by @syssi  with an easun inverter after i would miss the bms (now i'm using the serial Bluetooth connection i don't know if it is possible with an esp board) to be integrated via esphome instead of the current raspberry and mqtt

**Comment by syssi** [comment]
@lucasimons Which BMS do you use?

**Comment by lucasimons** [comment]
i have a bms like this  [BMS](https://it.aliexpress.com/item/32997552090.html?spm=a2g0s.9042311.0.0.27424c4dvSMF6Q) has no serial ports or at least i think and i currently use a script in py to extrapolate the data and publish it via mqtt, but I saw on this  [forum](https://diysolarforum.com/threads/for-those-of-you-looking-to-monitor-your-ant-bms-with-pi3-via-bluetooth.6726/page-3) that if you wanted there would also be the possibility of controlling the charge and discharge mosfets but I could not

BTW, I can control the BMS now. The checksum is just the sum of the 3 bytes (address + data + data).

So.... sending it:

'A5A5FA0000FA' # Turn Off Charge MOSFET
'A5A5FA0001FB' # Turn On Charge MOSFET
'A5A5FE0000FE' # Reboot BMS
'A5A5F90000F9' # Turn Off DisCharge MOSFET
'A5A5F90001FA' # Turn On DisCharge MOSFET
'A5A5FC0000FC' # Toggles balancing

**Comment by syssi** [comment]
You could try to open the BMS and solder some wires to the RX/TX pins of the BLE daughterboard:

https://user-images.githubusercontent.com/14097148/67513889-6faa1e00-f6a4-11e9-94c1-70b825f00976.png

**Comment by lucasimons** [comment]
Currently I have a bms that I have disassembled and opening it actually has this board ble so should I connect these 4 cables?
![IMG_20210901_135513.jpg](https://user-images.githubusercontent.com/67467751/131667476-90c68389-a86d-44e6-8173-8fee5c1f0f4b.jpg)

**Comment by syssi** [comment]
Don't connect VCC because the module is already powered by the BMS. RX, TX and GND is sufficient. Take a look at the bottom of the circuit board (left and right corner). You could try to trace (measure the resistance) between all of this pins and the RX and TX pin of the BLE module. I assume there is a connection. Just the jack is missing.

**Comment by lucasimons** [comment]
I checked the continuity of all the connections that seem to be set up but I only found these two,
![InkedInkedIMG_20210901_135937_LI](https://user-images.githubusercontent.com/67467751/131678735-5670e1d5-6bdf-405f-9a5c-3539eddb7e4f.jpg)


 I don't know if it makes sense to continue writing here or directly open a new repository and document everything there

**Comment by syssi** [comment]
Yes. We shouldn't hijack this issue and repository. Feel free to ping me if you need support. I'm trying to build a powerwall using a JK BMS at the moment: https://github.com/syssi/esphome-jk-bms

**Comment by lucasimons** [comment]
perfect I had seen your repo in fact I had found that of the inverter that I will test shortly then in case I continue with the bms
