### ISSUE TITLE
phenix-inverter / multi RS solar POWER

### ISSUE THREAD

**Issue by cristof48** [KinDR007/VictronMPPT-ESPHOME#80]
hello, is it possible to add in the esphome code for multi RS solar, a "Sensor/fonction" for power as 
OUT POWER = AC_OUT_I  x  AC_OUT_V.
thanks.

**Comment by syssi** [comment]
If you want to integrate the power to kWh later on you should stick to the first solution because of

https://github.com/esphome/issues/issues/2793#issuecomment-988257209
